services:
  Craue\ConfigBundle\Controller\SettingsController:
    class: Craue\ConfigBundle\Controller\SettingsController
    calls:
      - setContainer: ['@service_container']
    tags:
      - controller.service_arguments
