parameters:
  craue_config.redirectRouteAfterModify: craue_config_settings_modify

services:
  craue_config_cache:
    class: Symfony\Component\Cache\Adapter\NullAdapter
    public: false

  craue_config_default:
    class: Craue\ConfigBundle\Util\Config
    public: true
    arguments:
      - '@craue_config_cache'
    calls:
      - setEntityManager: ['@doctrine.orm.default_entity_manager']
      - setEntityName: ['%craue_config.entity_name%']

  craue_config:
    alias: craue_config_default
    public: true

  # autowiring alias
  Craue\ConfigBundle\Util\Config:
    alias: craue_config_default
    public: false
